### ISSUE TITLE
replace the system() call to do fork()/socketpair()/exec()  

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#106]
The current system() call used by aca does not handle timeout and reading the output of the command. We want to replace system() and do fork()/socketpair()/exec() to allow those capabilities.

**Comment by er1cthe0ne** [comment]
I like the idea of Aca_Net_Config will keep its own interface unchanged.

>>> The question is where would the lower level functions in use by aca_system() implemented? One possibility is in the same module as aca_system() meaning in aca_net_config.cpp. The second is to create a library directory for it and then at link it, but I am not sure if it make sense or it is worth in the global scheme of things.

Same module is easier, we can put the code either in aca_net_config.cpp or place it in another file in the same directory.

**Comment by spagochitarra** [comment]
Hi, indeed the same module is easier and it can be extended later anyway. We can add the few functions in the same namespace.

**Comment by spagochitarra** [comment]
After implementing and testing the feature I have found that there is not much performance gain in using the new method. The data are collected by running aca_test, then grep for the milliseconds printed by the message 'Elapsed time for system command took'. Based on these we can compute the average value of all operations which is 60.4 ms with aca_system() versus 40.748 with system(). 
This could reflect the fact that system() is in libc which is optimized. 

The distribution of runtime give a better idea than averages. Here 2 histograms of 100 runs of the test. One histogram is centered around 25ms which is the median value of the distribution.

![100 median](https://user-images.githubusercontent.com/62913361/83882657-6f7d0100-a710-11ea-98b8-cfd859052b53.png)
![100](https://user-images.githubusercontent.com/62913361/83882662-70159780-a710-11ea-90f7-cc1f563ad145.png)

The data show there is really not much difference between the 2 methods for most of the data point.
The advantage of aca_system() is the explicit call timeout to prevent hanging. 

Please let me know if you think it is still worth to push this code change.

Thanks,
David

**Comment by xieus** [comment]
@spagochitarra This is very nice. One quick question: for each test run, do we trigger multiple calls in parallel or just one?

**Comment by spagochitarra** [comment]
The code speaks :-) This is the test.

# cat testme 
#!/bin/bash

for ((i=0; i<10; i++))
do
   ./aca_tests
#   sleep 1
done

I assume serial execution.

**Comment by xieus** [comment]
Cool. Not so complicated :-) 

I have a suggestion: could we trigger multiple calls in parallel (in aca_tests or a new test script like paralle_aca_tests, you name it), and increase the concurrency all the way up to 1,000? We should start seeing some differences between the two.

**Comment by spagochitarra** [comment]
Simplicity reveals complexity :-) 

By parallel execution do you mean running multiple aca_tests at the same time. Basically sending them all in background with &?

**Comment by er1cthe0ne** [comment]
I can suggest a relatively simple way to do parallel execution to the aca_system call.

1. Add a new test case in aca_test.cpp to call aca_system in 100 threads in parallel "TEST(system_test_cases, aca_system_call)". This will simulated how aca handles 100 port states inside a single goal state. See Aca_Net_State_Handler::update_port_state_workitem
2. Execute just that test case by "./build/tests/aca_tests --gtest_filter=*aca_system*

**Comment by spagochitarra** [comment]
Hi, I can create a test function like TEST(system_test_cases, aca_system_call) but how to create 100 threads inside? By calling pthread_create() in a loop? Also if I run it as --gtest_filter=aca_system the function does not get called. I think I need a bit more guidance on how to use this framework.
Thanks

**Comment by er1cthe0ne** [comment]
> Hi, I can create a test function like TEST(system_test_cases, aca_system_call) but how to create 100 threads inside? By calling pthread_create() in a loop? 

Hi, you can use similar code in Aca_Net_State_Handler::update_port_states

> Also if I run it as --gtest_filter=aca_system the function does not get called. I think I need a bit more guidance on how to use this framework.

Sorry, I missed the important '*", it is needed because gtest framework append the  test group name in the front, try this: "./build/tests/aca_tests --gtest_filter=*aca_system*"

**Comment by spagochitarra** [comment]
Hi, thanks for the directions. I implemented the test case. In order to compare execution times I ran a serial and a parallel tests in the same function. I run a simple 'l/bin/ls ls > /dev/null' When using system() the serial execution is many times faster then using futures. The serial execution is more efficient than parallel, on average 1.23ms versus 32.2451ms.

The same performance pattern happens with aca_system() 1.36ms in the serial run vs 95.94ms in the parallel case. Also aca_system() is not thread safe as it uses global process is and descriptors across calls. A mutex would need to be implemented if the parallel uses case is needed.

**Comment by er1cthe0ne** [comment]
Hi, this is good data. Are you running the test on a server class machine with a lot of CPUs (e.g. 40 cores)? I am asking that because we were seeing better numbers (like 7x) with parallel processing, but our test were doing more stuff than just doing system(). :)

We will need to make aca_system() as thread safe because we have parallel execution by default when processing multiple goal states configurations. I wonder how big the impact would be when we put in a mutex to support parallel case. Previously, we simply called system() and let the OS handle lockings if needed.

**Comment by spagochitarra** [comment]
I ran on a vm with 2 cores. When I mentioned mutex I was referring to the current code, aca_system() can be made thread safe without mutexes.

**Comment by er1cthe0ne** [comment]
Hi, for the current code, we are relying the underneath command implementation to ensure thread safety. It is similar to a user or programming running multiple commands which I assume the OS should be able to handle. Do you see risk of relying on that?

http://www.cplusplus.com/reference/cstdlib/system/:
Concurrently calling this function with a null pointer as argument is safe. Otherwise, it depends on the system and library implementation.

**Comment by spagochitarra** [comment]
Hi, I think the current usage is fine, system() has been around since ages and the man page says it is thread safe.

When I mentioned mutex I was thinking about the current aca_system() implementation only. The aca_system() does what system() does but it adds the possibility to timeout the call which system does not.

**Comment by er1cthe0ne** [comment]
Cool, we are in the same page now. Let's make aca_system() thread safe. You can go ahead to submit a PR on the current change which may help with the technical discussion.

The current outstanding point is, after added thread safe implementation, will aca_system() performance be acceptable when running parallel in multiple threads (e.g. 100).

**Comment by spagochitarra** [comment]
I have made if pthread safe. The performance for the parallel case does not improve, system() has the same issue. However this could be cause by the way the test is written, it may be done wrongly. :-)
I am going to submit a pull request please help me to fix the test case.

**Comment by spagochitarra** [comment]
It is the container that slows things down. 

The code below with 1000 threads takes ~300ms on the vm with 4 cores and 4GB of ram but it takes ~1.5secs in the container on the same vm. If we put this testing code inside aca 1 second over is added and the total to ~2.5secs. This is pure system with the aca_system() call removed from the code.

-----------------------------------------------------------------------------------------------------------------------------
#include <future>
#include <iostream>
#include <vector>
#include <time.h>
#include <sys/time.h>

#define NUM_THREADS 1000

using namespace std;

static int
call_me(int i)
{
    system("/bin/ls > /dev/null");
    // cout << "thread number " << i << endl;
    return i;
}

int
main()
{
    std::vector<std::future<int>> futures;
    struct timeval st;
    struct timeval et;

    gettimeofday(&st, NULL);
    for (int i = 0; i < NUM_THREADS; i++) {
        futures.push_back(std::async(call_me, i));
    }

    for (auto &e : futures) {
        //cout << e.get() << endl;
    }
    gettimeofday(&et, NULL);

    time_t elapsed = (et.tv_sec - st.tv_sec) * 1000
        + (et.tv_usec - st.tv_usec)/1000;

    cout << "ran for "<< elapsed << " ms" << endl;

    return 0;
}

**Comment by spagochitarra** [comment]
I ran the futures code on a much better vm and it took between 0ms to 1 ms.

**Comment by er1cthe0ne** [comment]
> The code below with 1000 threads takes ~300ms on the vm with 4 cores and 4GB of ram but it takes ~1.5secs in the container on the same vm. If we put this testing code inside aca 1 second over is added and the total to ~2.5secs. This is pure system with the aca_system() call removed from the code.

Good information. Let's also get the numbers when we run system() serially to show the parallel processing provides improvement as we expected. Can we get the numbers for aca_system() with similar setup? Thanks.

**Comment by spagochitarra** [comment]
Using just system() we see the numbers below, I am expecting to see the same with aca_system() + the aca overhead.

With **no** container we have:

``
serial ran for 1303 ms 
``
``
parallel ran for 236 ms
``
``
``

**inside** the container

``
serial ran for 1144 ms 
``
``
parallel ran for 1415 ms
``

Parallel is slower, which seems unexpected. In the container I always see the process in D state waiting for IO which I think is done with the cgroup file system.

**Comment by er1cthe0ne** [comment]
> I am expecting to see the same with aca_system() + the aca overhead.
We will let the numbers speaks. Let's focus on the no container setup since the serial vs parallel number makes more sense. I understand it may take some work to port aca_system into it but I think it is important show the performance is expected for the parallel execution.

**Comment by er1cthe0ne** [comment]
Hi David,

Just checking to see how is the work going. Let me know if you need anything from me. @spagochitarra

**Comment by spagochitarra** [comment]
Hi, @er1cthe0ne I did not get time to get back to this issue for now. Sorry for the delay.

**Comment by er1cthe0ne** [comment]
> Hi, @er1cthe0ne I did not get time to get back to this issue for now. Sorry for the delay.

Hi @spagochitarra , got it. Please let me know how much time you are available to work on this so that I can have some expectation on my side. Thanks.

**Comment by spagochitarra** [comment]
Hi @er1cthe0ne I am sorry to say that at this time I cannot pursue this task anymore. 

Thanks

**Comment by er1cthe0ne** [comment]
closing old issue.
