### ISSUE TITLE
aca test falure

### ISSUE THREAD

**Issue by spagochitarra** [futurewei-cloud/alcor-control-agent#107]
After I run the test in loop few hundred times I observe failures:

[==========] 18 tests from 1 test suite ran. (1067 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] net_config_test_cases.create_namespace_valid
[  FAILED  ] net_config_test_cases.create_veth_pair_valid
[  FAILED  ] net_config_test_cases.setup_peer_device_valid
[  FAILED  ] net_config_test_cases.move_to_namespace_valid
[  FAILED  ] net_config_test_cases.setup_veth_device_valid
[  FAILED  ] net_config_test_cases.rename_veth_device_valid

I have captured some of the failures:

Elapsed time for system command took: 1300363 nanoseconds or 1 milliseconds.
Command failed!!!: ip netns add test_ns
/mnt/host/code/test/gtest/aca_tests.cpp:93: Failure
Expected equality of these values:
  rc
    Which is: 256
  0

Did I used up some resource?

Thanks,
David

**Comment by spagochitarra** [comment]
I see the errors even after I restart the container.

**Comment by er1cthe0ne** [comment]
> Did I used up some resource?
> 
> Thanks,
> David

Yes, looks like it used up some system resources to the point that "ip netns add test_ns" is no longer working. #106 could be useful to see the error output, and we have motivation to use netlink library so that we can better error handling for the "ip netns" call.

Note that each test case already tried to cleanup all the allocated resources. So it is not clear whether it is the "ip netns" calls or mizar dataplane ACA handling call that's consuming system resources. Since the container is using the host system resources, reboot the host may help.

**Comment by xieus** [comment]
@er1cthe0ne Please take a look to see if the failure is blocking or transient (fixed once your latest PR https://github.com/futurewei-cloud/alcor-control-agent/pull/105 is in).

**Comment by er1cthe0ne** [comment]
> @er1cthe0ne Please take a look to see if the failure is blocking or transient (fixed once your latest PR #105 is in).

I don't think it is blocking and we can revisit this after PR #105 since it will reramp many of the test cases.

**Comment by xieus** [comment]
> > @er1cthe0ne Please take a look to see if the failure is blocking or transient (fixed once your latest PR #105 is in).
> 
> I don't think it is blocking and we can revisit this after PR #105 since it will reramp many of the test cases.

Okay. It seems that the current agent build check and CI both missed the test failure.
Do we enable tests there? If not, let us plan to fix failed tests and enable it in our CI shortly.

**Comment by er1cthe0ne** [comment]
> > > @er1cthe0ne Please take a look to see if the failure is blocking or transient (fixed once your latest PR #105 is in).
> > 
> > 
> > I don't think it is blocking and we can revisit this after PR #105 since it will reramp many of the test cases.
> 
> Okay. It seems that the current agent build check and CI both missed the test failure.
> Do we enable tests there? If not, let us plan to fix failed tests and enable it in our CI shortly.

The failure happens after running the test in loop few hundred times. 

We didn't enable the test in CI yet, we can enable it after PR #105 is in.

**Comment by spagochitarra** [comment]
I think this is the problem:

./aca_tests|grep Elapsed

the pipe on stdout somehow screws up the things for good. If I ran it once or twice it just gives an error but the follow up aca_tests still work

Errors:
nanoseconds or 59 milliseconds.
localhost: RPC: Port mapper failure - RPC: Unable to receive
localhost: RPC: Port mapper failure - RPC: Unable to receive
localhost: RPC: Port mapper failure - RPC: Unable to receive
localhost: RPC: Port mapper failure - RPC: Unable to receive
localhost: RPC: Port mapper failure - RPC: Unable to receive

however if I put it in loop:

#!/bin/bash

for ((i=0; i<1000; i++))
do
   ./aca_tests|grep Elapsed
#   sleep 1
done

the test does not work anymore. I can reboot the container, the vm and even the machine that hosts the vm. The only solution is to rebuild the container, I use a different name, and damage it again :-)

David

**Comment by er1cthe0ne** [comment]
> localhost: RPC: Port mapper failure - RPC: Unable to receive
> localhost: RPC: Port mapper failure - RPC: Unable to receive
> localhost: RPC: Port mapper failure - RPC: Unable to receive
> localhost: RPC: Port mapper failure - RPC: Unable to receive

If that's the problem, we can move on because these set of test case will be deactivated after PR #105 is in. :)

**Comment by spagochitarra** [comment]
Ok. Understood.
