### ISSUE TITLE
Add ARP responder for both L2 and L3 neighbors

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#117]
When ACA receives L2 and L3 neighbor configuration from Alcor controllers, it contains the IP and MAC mapping for each L2 and L3 neighbor. ACA should remember this information by in some new data structure. 

We already have arp reponder logic in place to repond to arp request targetted to the gateway interfaces connected to alcor distributed router:

ovs-ofctl add-flow br-tun "table=51,priority=50,arp,dl_vlan=1,nw_dst=10.0.0.1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],mod_dl_src:02:42:ac:11:00:01,load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],load:0x0242ac110001->NXM_NX_ARP_SHA[],load:0x0a000001->NXM_OF_ARP_SPA[],in_port"
ovs-ofctl add-flow br-tun "table=0,priority=25,arp,arp_op=1,in_port="patch-int" actions=resubmit(,51)"
ovs-ofctl add-flow br-tun "table=51,priority=1,actions=resubmit(,22)"

To support cloud scale, we will not want to plumb down static arp responder rules which can over populate the openflow table. We will do a smart way by punting all the arp packet to openflow controller (that's ACA), and let it repond to ARP for know IP address. Therefore the logic would look like:

1. All the arp request packets sends to openflow controller (ACA)
2. ACA look up internal data structure to see if the ARP IP is known
2a. if ARP request IP is known to ACA, ACA will craft an ARP response packet back with the corresponding mac
2b. if ARP request IP is not known, send it out to the wire like other packet

Additional Zeta info, once Zeta support is added to ACA, a port will be marked as non-Zeta supported or Zeta supported.
1. For non-Zeta supported port, follow the logic mentioned above
2. For Zeta support port, send the packet to the Zeta Gateway because it will be the arp responder.
You may not need to do anything ideally, but just keep the Zeta logic in mind to make sure we follow it.

__Action items__

0. review the DHCP code to see how to install the punt rule to punt DHCP packet to ACA, how it process the DHCP packet and craft a DHCP respond packet back
1. remove the below existing ARP table implementation, we don't need it anymore:
ovs-ofctl add-flow br-tun "table=0,priority=25,arp,arp_op=1,in_port="patch-int" actions=resubmit(,51)"
ovs-ofctl add-flow br-tun "table=51,priority=1,actions=resubmit(,22)"
2. create a new file under /src/ovs named aca_arp_responder.cpp, make it singleton like other classes
3. add a new class ACA_ARP_Responder in the above file, constructor and destructor will add or remove the punt rule, similar to ACA_Dhcp_Server::ACA_Dhcp_Server
4. the new class to add a new data structure to remember (internal vlan ID, IP) to mac mapping
5. add functions to add/remove entry in 4, also add functions to receive and send arp packet, similar to ACA_Dhcp_Server::ACA_Dhcp_Server
6. modify router gateway add code, and also L2 and L3 neighbor processing code to call functions in 5, need to figure out if we need to process arp request for L2 and L3 neighbors differently (maybe not)
7. modify aca_ovs_control.cpp, so that arp packet will be send to ACA_ARP_Responder class for processing, similar to the current dhcp code: aca_dhcp_server::ACA_Dhcp_Server::get_instance().dhcps_recv

**Comment by lly00** [comment]
@er1cthe0ne I don't clearly understand  what we need to do in 3b  

> need to remove the on demand rule

Could you explain it to me?

**Comment by er1cthe0ne** [comment]
> Could you explain it to me?

@lly00 I have updated the discription on this issue based on the current thinking. Please take a look.

**Comment by er1cthe0ne** [comment]
@lly00 - I confirmed in the code that we have access to vlan of the packet. Please see the first session of the below function in aca_ovs_control.cpp:

void ACA_OVS_Control::parse_packet(uint32_t in_port, void *packet)

You may need to modify that function to extract the vlan and pass it into your new functions.

**Comment by lly00** [comment]
> @lly00 - I confirmed in the code that we have access to vlan of the packet. Please see the first session of the below function in aca_ovs_control.cpp:
> 
> void ACA_OVS_Control::parse_packet(uint32_t in_port, void *packet)
> 
> You may need to modify that function to extract the vlan and pass it into your new functions.

Okay, I'll take a look

**Comment by er1cthe0ne** [comment]
@lly00 - please focus on doing the ARP responder for L2 neighbors. When a port trying to ARP is L3 neighbor, it would simply ARP its default gateway.
