### ISSUE TITLE
[Enhancement] Raise compiler warning level

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#138]
__Issue Description__

One of the best tool to catch code issues is to use the compiler to display warnings during compile time. ACA already have setting to have the compile to display most common warnings using the '-Wall' flag (under /CMakeLists.txt). We want to enable extra warning levels in ACA slowly fix any new warnings pop up. We can start with enabling the below warning displays:

'-Wextra'
'-pedantic -Wpedantic'
'-Werror'

Detail explaination of different compiler flags for warning are at: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

__Action items__

0. Get a development environment setup based on https://github.com/futurewei-cloud/alcor-control-agent/blob/master/src/README.md
1. get familiar with what different compiler flags for warning means: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
2. add new warning flags in /CMakeLists.txt, start with '-Wextra', then '-pedantic -Wpedantic', and then '-Werror'
3. fix issues for any new compile warnings pop up due to the flag change, then enable the next warning flag

__Update__

Since ACA is under active development, raising the warnings now (-Wall -Wextra -pedantic -Wpedantic) and marking them as compile time error (-Werror) is like trying to hit a moving target. Let's do this in two stages:

1. go ahead to raise the warning now in /cMakeLists.txt: add_compile_options(-Wall -Wextra -pedantic -Wpedantic), rebase your PR because of current new changes. Note that we just took in a new pulsar dependancy so you will need to update or rebuild your development environment. Try to complete that PR first with the goal of merge it in soon.

2. once everyone start seeing and fixing their new compile time warning, when all the warnings are fixed, we can tell compile to show all warning as errors: /cMakeLists.txt: add_compile_options(-Wall -Wextra -pedantic -Wpedantic -Werror)

**Comment by Zqy11** [comment]
I have installed the ACA, and I'm getting familiar with ACA

**Comment by er1cthe0ne** [comment]
> I have installed the ACA, and I'm getting familiar with ACA

That's great, I have assigned this issue to you. Do let us know if you have any questions.
