### ISSUE TITLE
[Enhancement] use valgrind to confirm there is not memory leak

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#139]
__Issue Description__

valgrind is a great tool to look for memory leak for a program. We want to run it with latest AlcorControlAgent to confirm there is no memory leak, fix any issue reported by the tool.

__Action items__

0. Get a development environment setup based on https://github.com/futurewei-cloud/alcor-control-agent/blob/master/src/README.md
1. install valgrind: "apt-get update -y && apt-get install -y valgrind"
2. execute the tool: "valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes ./build/bin/AlcorControlAgent"
3. review any memory leak flagged by tool, fix the memory leak issue if appropriate
4. once everything has been fixed, ask valgrind to check for more memory check problems :)

**Comment by zhangml** [comment]
Ok, I am responsible for this issue.

**Comment by er1cthe0ne** [comment]
> Ok, I am responsible for this issue.

That's great, I have assigned this issue to you. Do let us know if you have any questions.

**Comment by er1cthe0ne** [comment]
FYI, here is the output I see from my environment, we should focus on investigate and fixing the "possibly lost".

==1634== LEAK SUMMARY:
==1634==    definitely lost: 0 bytes in 0 blocks
==1634==    indirectly lost: 0 bytes in 0 blocks
==1634==      possibly lost: 2,166 bytes in 8 blocks
==1634==    still reachable: 80,557 bytes in 257 blocks
==1634==         suppressed: 0 bytes in 0 blocks
==1634== 
==1634== For counts of detected and suppressed errors, rerun with: -v
==1634== ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 0 from 0)

To check the ACA logs:
root@28abfb290c2e:/mnt/host/code/aca-dev# vim /var/log/syslog

**Comment by er1cthe0ne** [comment]
@zhangml - for the grpc thread leak you mentioned detected by valgrind. I think it caught a good issue. 

It is likely due to the fact that we started a new thread for grpc server but didn't really join and clean up the thread before program exit. See line 184 in aca_main.cpp (g_grpc_server_thread = new std::thread(std::bind(&GoalStateProvisionerImpl::RunServer, g_grpc_server));

A possible way to address this is to add code in aca_cleanup function in aca_main.cpp to clean up the new thread.

**Comment by zhangml** [comment]
I have added the code to clean up the thread in aca_clean(), but the situation has not changed. I called the join() function of the thread in the main thread and found that the main() method would block here. I guess it is because grpc thread executes server->wait() after executing Runserver()（aca_grp.cpp  line95） method. If no other thread calls server->shutdown(), the thread will be blocked here. In the original program, main() does not have a thread join() method, so the main thread exits before the grpc thread. I think the solution may be to use other threads to call the server->shutdown() method. @er1cthe0ne

**Comment by zhangml** [comment]
I did a simple test. I commented out server->Wait() directly and got the following results.
==32654== LEAK SUMMARY:
==32654==    definitely lost: 0 bytes in 0 blocks
==32654==    indirectly lost: 0 bytes in 0 blocks
==32654==      possibly lost: 0 bytes in 0 blocks
==32654==    still reachable: 13,473 bytes in 85 blocks
==32654==         suppressed: 0 bytes in 0 blocks
==32654==
==32654== For counts of detected and suppressed errors, rerun with: -v
==32654== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
This verifies that the cause of the memory leak is that the grpc thread is blocked indefinitely.

**Comment by er1cthe0ne** [comment]
@zhangml - this is very good confirmation. 

Looks like it will be useful to call ::Shutdown method: 

https://github.com/grpc/grpc/issues/10324

Let's add that in the destructor: ~GoalStateProvisionerImpl() to see if that address the memory leak.

Please review the information in the links below to see if it helps:

https://stackoverflow.com/questions/32504208/how-to-shutdown-grpc-server-from-client-using-rpc-function
