### ISSUE TITLE
[Documentation] Zeta integration design document

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#147]
__Context__

We need to have a complete ACA with Zeta intergration design document which has enough detail to the point that anyone can follow it and then make the change in ACA.

__Purpose__

1. Close down on all the major design decision
2. Provide understanding of major workflows
3. Identify design gaps and address open questions
4. Serve as the contract for our opensource development

__Action items__

1. Create a new document under /docs directory named zeta_integration.adoc, add the corresponding linkage in table_of_content.adoc
2. Include highlevel achitecture diagram
3. Include major design points:
3a. bucketing system to send traffic to Zeta gateway
3b. OAM packet usage and handling 
4. Include proposed code changes:
4a. Goal state message change from Alcor server to ACA
4b. How to send traffic to different buckets
4c. OAM packet handling
4d. Test code updates
5. Sample openflow rules for bucketing and OAM packet send to ACA
6. Include workflow diagram for bucketing and OAM handling

see this as an example: https://github.com/futurewei-cloud/alcor/blob/master/docs/modules/ROOT/pages/high_level/routing_design.adoc

**Comment by HuaqingTu** [comment]
Hi. Eric. I will follow up on this issue :)

**Comment by er1cthe0ne** [comment]
> Hi. Eric. I will follow up on this issue :)

@HuaqingTu - cool, I have assigned this issue to you. Do let me know if you have any questions on this.

**Comment by HuaqingTu** [comment]
To be honest, I have not written such a design before, and the projects I have done are limited, should I write a version first according to my understanding? This version may be native.

**Comment by er1cthe0ne** [comment]
> To be honest, I have not written such a design before, and the projects I have done are limited, should I write a version first according to my understanding? This version may be native.

No problem. I will guide you on this as I have done this a few times already. My suggestion is to:

1. start a draft document in your branch
2. put in the highlevel sessions titles, can leave the body empty of "TBD" in the beginning
3. start a PR from your branch so I can look at your current status and comments on it
4. I can also fill in your document when I have time :)
