### ISSUE TITLE
[Documentation] Manual construction and testing of openflow rule for Zeta integration

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#148]
__Context__

We need to manually write up the setup of openflow rules needs for Zeta, including:

1. the bucketing rules to send packets to Zeta gateway
2. the punt rule to send OAM packet to ACA

__Action items__

1. get familiar with the needed openflow rules
2. run it in a test environment, send traffic and OAM like packet to exercise the new rules
3. use tcpdump to observe the packet behavior
4. the idea is if we can make it work using manual openflow rules, when we can make it work using ACA code
5. document the manual rules in #147

**Comment by Zqy11** [comment]
I am Qianyu Zhang and I will be responsible for this issue.

**Comment by er1cthe0ne** [comment]
> I am Qianyu Zhang and I will be responsible for this issue.

Sounds good. I have assigned this issue to you. Do let us know if you have any questions.

**Comment by er1cthe0ne** [comment]
Hi @Zqy11 - we are making good progress on the design discussion. One thing we need to move forward is to understand what is the exact information needed to construct the group bucketing openflow rules. Please continue with your manual rule exercise and provide an update here. Thanks.
