### ISSUE TITLE
[Zeta] redundant ARP request for Zeta node 

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#195]
**Context**
Zeta group rule leverage the Zeta node destination IP and destination MAC for vxlan packet forwarding. Since the destination mac is already filled in by group rule, the expectation is no ARP request for destination IP is needed.

**Expected**
1.  no ARP request for destination IP is sent
2. tunnel packet will be forwarded to Zeta node

**Actual**
1. ARP request for destination IP is sent
2. tunnel packet did not get forwarded to Zeta node

I have emailed ovs-dev on this and waiting for response.

**Comment by liangbin-pub** [comment]
Fall back plan is to use the ZGC entries information to populate static ARP, static ARP method has been validated working.

**Comment by er1cthe0ne** [comment]
perhap this behavior is due to the fact that we didn't specify a physical interface or IP in our vxlan-generic port, and that trigger the linux networking stack to send ARP request to looking for the best local interface to use. Let's try to add the tenant network interface IP into the vxlan-generic port to see if that helps. 

It will require changing of aca code in aca_ovs_l2_programmer.cpp, line 149 from:

    execute_ovsdb_command(
            string("--may-exist add-port br-tun vxlan-generic -- set interface vxlan-generic ofport_request=") +
                    VXLAN_GENERIC_OUTPORT_NUMBER +
                    " type=vxlan options:df_default=true options:egress_pkt_mark=0 options:in_key=flow options:out_key=flow options:remote_ip=flow",
            not_care_culminative_time, overall_rc);

to:

    execute_ovsdb_command(
            string("--may-exist add-port br-tun vxlan-generic -- set interface vxlan-generic ofport_request=") +
                    VXLAN_GENERIC_OUTPORT_NUMBER +
                    " type=vxlan options:df_default=true options:egress_pkt_mark=0 options:in_key=flow options:local_ip=192.168.20.92 options:out_key=flow options:remote_ip=flow",
            not_care_culminative_time, overall_rc);

**Comment by er1cthe0ne** [comment]
response from ovsdev:

> 1. Who trigger this unneeded ARP request?
When OvS tries to send tunnel packets, OvS will use the arp, if there
is no arp, request it.

> 2. Can we disable this behavior?
I add a feature, then OvS can learn arp from linux kernel. In other
words, we disable it ?
http://patchwork.ozlabs.org/project/openvswitch/list/?series=220295

**Comment by er1cthe0ne** [comment]
> Fall back plan is to use the ZGC entries information to populate static ARP, static ARP method has been validated working.

adding options:local_ip=192.168.20.92 for vxlan-generic port doesn't help. This confirms the ovsdev statement above. We will go with the fallback plan mentioned by @liangbin-pub .

@zhangml there are two action items to execute the fallback plan. Please go ahead to add the static arp entries ("arp -s ipaddr macaddr) when creating the group rule, remove the static arp entries when deleting the group rule.
