### ISSUE TITLE
[Zeta] update to use the latest Alcor gateway schema

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#201]
Context:

The gateway schema was recently updated based on latest gateway design. It moved the gateway configuration as a top level resource: https://github.com/futurewei-cloud/alcor/blob/master/schema/proto3/gateway.proto

and vpc configuration linked to it by gateway_ids: https://github.com/futurewei-cloud/alcor/blob/master/schema/proto3/vpc.proto

Action items:

1. Update Alcor submodule to the latest master, to consume the latest Alcor gateway schema
2. ACA change to consume the latest gateway schema, it would use the gateway_ids from vpc configuration to "look up" the gateway configuration

**Comment by zhangml** [comment]
@er1cthe0ne I don't quite understand why there is no gatewaystate in GoalState? Where is the gateway message obtained from?
https://github.com/futurewei-cloud/alcor/blob/master/schema/proto3/goalstate.proto

**Comment by er1cthe0ne** [comment]
You are right, I have fixed that in https://github.com/futurewei-cloud/alcor/pull/543 . The change is approved and should be merged soon.
