### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor-control-agent#210]
We want to setup Travis CI for this repro. The steps are:

0. Get familiar with Travis CI, this is a good start: https://blog.travis-ci.com/2019-05-30-setting-up-a-ci-cd-process-on-github 
1. Enable Travis CI for this repro (done)
2. Setup a simple Travis in your Fork, which just setup the test environment and return pass :)
3. Review and leverage the Travis setup from Zeta: https://github.com/futurewei-cloud/zeta
4. Have our Travis CI to execute DISABLED_2_ports_CREATE_test_traffic_CHILD and DISABLED_2_ports_CREATE_test_traffic_PARENT instead of the Zeta test cases

**Comment by PikaPikaW** [comment]
Hello, I have seen The Travis Setup from Zeta and have some questions:
Does ACA need to create containers as ACA nodes, and does Zeta api need to get information like VPC and ports?
and before script something aca doesnot need:
```shell
before_script:
  - sudo apt-get update
  - sudo systemctl unmask docker.service
  - sudo systemctl unmask docker.socket
  - sudo systemctl start docker
  - sudo systemctl enable docker
  # Install Kind
  - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.9.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
  # Install Kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - pip3 install ansible
  - pip3 install docker
  - printf 'y\nn\n' | sudo ./tools/kernelupdate.sh
  # Build Zeta
  - ./build.sh debug
  # Build ACA
  - ./src/extern/alcor-control-agent/build/build.sh
  - yes | ./deploy/env_setup.sh
  ```
i think aca dosenot need Kind,Kubectl,ansible,kernelupdate.sh and doesnot need build Zeta

**Comment by er1cthe0ne** [comment]
> Hello, I have seen The Travis Setup from Zeta and have some questions:
> Does ACA need to create containers as ACA nodes, and does Zeta api need to get information like VPC and ports?

Travis will create two containers for the two ACA nodes (parent and child nodes). Zeta is not involved for this setup.

> i think aca dosenot need Kind,Kubectl,ansible,kernelupdate.sh and doesnot need build Zeta

that's correct :)
