### ISSUE TITLE
ACA Crashes when Processing a Large Number of GoalStates at (Almost) the Same Time.

### ISSUE THREAD

**Issue by zzxgzgz** [futurewei-cloud/alcor-control-agent#248]
What happened:

When testing with the test controller, creating 375(or more) ports on each host, ACA crashes when all neighbor GoalStates are coming down from NCM. The last output of ACA is as follow:

```
[METRICS] Elapsed time for message total operation took: 13212 microseconds or 13 milliseconds
[METRICS] Elapsed time for gs printout operation took: 874 microseconds or 0 milliseconds
[METRICS] Elapsed time for router operation took: 0 microseconds or 0 milliseconds
[METRICS] Elapsed time for port operation took: 12336 microseconds or 12 milliseconds
[METRICS] Elapsed time for neighbor operation took: 0 microseconds or 0 milliseconds
[METRICS] Elapsed time for dhcp operation took: 1 microseconds or 0 milliseconds
Control Fast Path streaming - Successfully updated host with latest goal state 0.
[METRICS] Received goalstate at: [4767866448328698], update finished at: [4767866461592835]
Elapsed time for update goalstate operation took: 13264 microseconds or 13 milliseconds
[New Thread 0x7fffecff9700 (LWP 27786)]
[Thread 0x7fffc9ffb700 (LWP 27545) exited]
[Thread 0x7fff83fff700 (LWP 27717) exited]
[Thread 0x7fffcaffd700 (LWP 27713) exited]
[Thread 0x7fffcb7fe700 (LWP 27353) exited]
[Thread 0x7fffabfff700 (LWP 27670) exited]

Thread 1012 "grpcpp_sync_ser" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed7fa700 (LWP 27356)]
0x00007ffff719b2db in vconn_connect (vconn=vconn@entry=0x0) at lib/vconn.c:548
548	lib/vconn.c: No such file or directory.
(gdb) client_loop: send disconnect: Broken pipe
```

This has happened multiple times, and ACA always crashes at this place.

**Comment by xieus** [comment]
So 375 is the magic number. Do we check the resource consumption on the machine that hosts ACA?

**Comment by zzxgzgz** [comment]
@xieus it might be the magic number, and turns out the the problem is about memory.

This is some interesting logs we found:
```
OVS_Control::flow_mod ---> Entering
Executing flow_mod on bridge: br-tun, flow: table=20,priority=50,dl_vlan=1,dl_dst:6c:dd:ee:0:3:32,actions=strip_vlan,load:21->NXM_NX_TUN_ID[],set_field:10.213.43.93->tun_dst,output:100, command: 0
br-tun: failed to open socket (Too many open files)/var/run/openvswitch/br-tun.mgmt: failed to open socket (Too many open files)/var/run/openvswitch/br-tun.mgmt: failed to open socket (Too many open files)br-tun is not a bridge or a socketcurrent_SubnetConfiguration subnet ID: 27330ae4-b718-11ea-b3df-111111111113.
current_VpcConfiguration VPC ID: 2b08a5bc-b718-11ea-b3de-111111111112
```

It seems like that too many flow_mods are happening at the same time, so that there are too many calls for the br-tun.mgmt, and this file is not able to handle that many things using it at the same time.

**Comment by er1cthe0ne** [comment]
I believe the crash is in the OVS library which is compiled and used by ACA. Having too many flow mods happening at the same time is a problem, there are two possible things to do:

1. follow up with OVS dev to see if the performance limit is expected and crash is not a surprise - ovs-dev@openvswitch.org
2. limit the number of concurrent threads (which calls to OVS) to proportional to number of CPU (e.g. # of CPU times 2).

**Comment by zzxgzgz** [comment]
@er1cthe0ne thank you for your insight!

**Comment by zzxgzgz** [comment]
After applying a quick fix to allow more open files:
```
ulimit -n 100000
ulimit -c unlimited
```
we are able to run the 500 ports on each host test. 

However, when we run the 1000 ports on each host test, ACA still crashes with the following last message:
```
=====>parsing port state: 11111111-b718-11ea-b3de-10000019067
/var/run/openvswitch/br-tun.mgmt: failed to open socket (Protocol error)/var/run/openvswitch/br-tun.mgmt: failed to open socket (Protocol error)br-tun is not a bridge or a socket
```

To ultimately solve this, we may need a specialized channel to communicate with OVS, rather than having x(x=number of callers) clients trying to open the same file(`br-tun.mgmt` in this case).

**Comment by lfu-ps** [comment]
[https://github.com/futurewei-cloud/alcor-control-agent/pull/261](url)

Solved this issue in a fundamental refactoring of communication between aca and ovs which is the PR above. 

Tested 1000 ports successfully.
