### ISSUE TITLE
Comparing performance for synchronous and asynchronous gRPC servers on ACA.

### ISSUE THREAD

**Issue by zzxgzgz** [futurewei-cloud/alcor-control-agent#253]
According to https://github.com/futurewei-cloud/alcor-control-agent/blob/master/src/comm/aca_grpc.cpp#L88, the current gRPC server on ACA, which is responsible for receiving GoalStates and applying it to the ACA, is synchronous. 

We wonder if it will speed up the overall ping time, if we make it asynchronous(so that the receiving function doesn't block until the current goalstate is finished being applied)?

To get started on the C++ gRPC async APIs, please refer to https://grpc.io/docs/languages/cpp/async/

To add code to measure time elapsed from point A to point B inside ACA, please refer to https://github.com/zzxgzgz/alcor-control-agent/blob/time_measurement/src/ovs/aca_vlan_manager.cpp#L191 and its following few lines.

**Comment by er1cthe0ne** [comment]
I think this really depends on the NCM/DPM side on how to handle the async return from ACA which indicate the work is not done yet. What happen if the completion call from ACA comes later with a failure? 

One model to consider is both grpc sender and receiver would do the async streaming, similar to a work item queue approach (i.e. I will tell you when there are stuff to do, and I will give you update like pending/success/failed when I have the status). But that would require some good coordination on both sender and receiver side, and potentially add more threads to handle the work in flight...
