### ISSUE TITLE
Data Plane abstraction layer design 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor-control-agent#91]
To support multiple Data Plane implementation including OVS and Mizar, we plan to add a new DP abstraction layer in Alcor Control Agent so that APIs of various data plane implementations are "invisible" to control plane.

**Comment by er1cthe0ne** [comment]
https://github.com/xieus/alcor/blob/docs/design/docs/visionary_design/dataplane_abstraction.adoc
